#add all words you want to filter into filter_words, this also occurs POST PROCESSING, so now if you filter
#  the term "friday" it will drop that singular term, but WOULD NOT filter "friday night" since it doesn't match

import pickle
filter_words = set()
pickle_path = "C:/temp/NU/453/pickle/" #where do you want to read / write the phrase list / filters, etc.

filter_words.update(['year', 'week', 'month', 'day', 'hour', 'minute', 'time','past','morning','afternoon', 'evening', 'night'])
filter_words.update(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday','today','yesterday','tomorrow'])
filter_words.update(['january','february', 'march', 'april','may','june','july','august','september','october','november','december'])
filter_words.update(['jan','feb', 'mar', 'apr','jun','jul','aug','sep','oct','nov','dec'])
filter_words.update(['others', 'contrast','approach','change','response','people','possibility'])
filter_words.update(['recommendation', 'side','control','fact','win','attempt','amid','something','eg','isnt','ive','hes','im','ill'])
filter_words.update(['rky','dc','dny','rfla','rid', 'try','weve','pas','co','km','sens','rokla','am','cnn'])
filter_words.update(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'])
filter_words.update(['']) #this was added since the % symbol returns as a valid single token, and is then stripped
filter_words.update(['zero','one','two','three','four','five','six','seven','eight','nine'])
#============================== Pasted from team excel generator below =================================
filter_words.update(["157"])
filter_words.update(["497"])
filter_words.update(["505"])
filter_words.update(["abandonment"])
filter_words.update(["absence"])
filter_words.update(["abuse"])
filter_words.update(["academic"])
filter_words.update(["access"])
filter_words.update(["access road"])
filter_words.update(["accomplishment"])
filter_words.update(["account"])
filter_words.update(["accountability"])
filter_words.update(["accountant"])
filter_words.update(["accusation"])
filter_words.update(["achievement"])
filter_words.update(["acknowledgment"])
filter_words.update(["act"])
filter_words.update(["action"])
filter_words.update(["action plan"])
filter_words.update(["actionsspeaklouderthanwords realm"])
filter_words.update(["activist"])
filter_words.update(["activity"])
filter_words.update(["activity"])
filter_words.update(["actor"])
filter_words.update(["actuary"])
filter_words.update(["add"])
filter_words.update(["addition"])
filter_words.update(["address"])
filter_words.update(["address"])
filter_words.update(["admiration"])
filter_words.update(["admission"])
filter_words.update(["adulation"])
filter_words.update(["advance"])
filter_words.update(["advantage"])
filter_words.update(["advice"])
filter_words.update(["adviser business holding"])
filter_words.update(["advocate"])
filter_words.update(["affection"])
filter_words.update(["affiliate"])
filter_words.update(["aftermath"])
filter_words.update(["afterward"])
filter_words.update(["afterwards"])
filter_words.update(["age"])
filter_words.update(["age point"])
filter_words.update(["agency"])
filter_words.update(["agency head"])
filter_words.update(["agenda"])
filter_words.update(["agenda"])
filter_words.update(["agenda item"])
filter_words.update(["aggressor"])
filter_words.update(["agreement"])
filter_words.update(["ahead"])
filter_words.update(["aid"])
filter_words.update(["aim"])
filter_words.update(["air"])
filter_words.update(["aircraft"])
filter_words.update(["airline"])
filter_words.update(["airport"])
filter_words.update(["aisle"])
filter_words.update(["alabama"])
filter_words.update(["alarm"])
filter_words.update(["alert"])
filter_words.update(["allout"])
filter_words.update(["ally"])
filter_words.update(["ambassador"])
filter_words.update(["ambiguity"])
filter_words.update(["america"])
filter_words.update(["american"])
filter_words.update(["american official"])
filter_words.update(["amount"])
filter_words.update(["amount"])
filter_words.update(["analysis"])
filter_words.update(["analysis"])
filter_words.update(["analyst"])
filter_words.update(["analytics"])
filter_words.update(["andor"])
filter_words.update(["anger"])
filter_words.update(["animus"])
filter_words.update(["announcement"])
filter_words.update(["anonymity"])
filter_words.update(["answer"])
filter_words.update(["anthem"])
filter_words.update(["anthem"])
filter_words.update(["anticipation"])
filter_words.update(["antithesis"])
filter_words.update(["anxiety"])
filter_words.update(["anyone"])
filter_words.update(["anything"])
filter_words.update(["apartment complex"])
filter_words.update(["apology"])
filter_words.update(["apparatus"])
filter_words.update(["appearance"])
filter_words.update(["appleby"])
filter_words.update(["application"])
filter_words.update(["appointee"])
filter_words.update(["apprehension"])
filter_words.update(["approval"])
filter_words.update(["approval rating"])
filter_words.update(["apt"])
filter_words.update(["architect"])
filter_words.update(["area"])
filter_words.update(["arena"])
filter_words.update(["argentina"])
filter_words.update(["argument"])
filter_words.update(["arizona"])
filter_words.update(["arrangement"])
filter_words.update(["array"])
filter_words.update(["arrival"])
filter_words.update(["art"])
filter_words.update(["article"])
filter_words.update(["asia"])
filter_words.update(["aspect"])
filter_words.update(["assault"])
filter_words.update(["assessment"])
filter_words.update(["asset"])
filter_words.update(["assistance"])
filter_words.update(["assistant secretary"])
filter_words.update(["athlete"])
filter_words.update(["attack"])
filter_words.update(["attendance"])
filter_words.update(["attendee"])
filter_words.update(["attention"])
filter_words.update(["attention"])
filter_words.update(["attorney"])
filter_words.update(["attrition"])
filter_words.update(["audience"])
filter_words.update(["audit"])
filter_words.update(["august interview"])
filter_words.update(["aunt"])
filter_words.update(["austin"])
filter_words.update(["author"])
filter_words.update(["authority"])
filter_words.update(["authorization"])
filter_words.update(["average"])
filter_words.update(["axis"])
filter_words.update(["back"])
filter_words.update(["background"])
filter_words.update(["background check"])
filter_words.update(["background music"])
filter_words.update(["backing"])
filter_words.update(["backseat"])
filter_words.update(["bad"])
filter_words.update(["balance"])
filter_words.update(["ball"])
filter_words.update(["bang"])
filter_words.update(["bar"])
filter_words.update(["barrel"])
filter_words.update(["base"])
filter_words.update(["baseless claim"])
filter_words.update(["basis"])
filter_words.update(["battle"])
filter_words.update(["battle"])
filter_words.update(["bay"])
filter_words.update(["beaten"])
filter_words.update(["becomes"])
filter_words.update(["bed"])
filter_words.update(["beef"])
filter_words.update(["beginning"])
filter_words.update(["behalf"])
filter_words.update(["behavior"])
filter_words.update(["belief"])
filter_words.update(["bellicosity"])
filter_words.update(["bench"])
filter_words.update(["beneficiary"])
filter_words.update(["benefit"])
filter_words.update(["bfps venture"])
filter_words.update(["bid"])
filter_words.update(["bill"])
filter_words.update(["billion"])
filter_words.update(["billionaire"])
filter_words.update(["bit"])
filter_words.update(["blast"])
filter_words.update(["bloc"])
filter_words.update(["block"])
filter_words.update(["blood"])
filter_words.update(["blow"])
filter_words.update(["blow"])
filter_words.update(["blueprint"])
filter_words.update(["bluff"])
filter_words.update(["bluster"])
filter_words.update(["board"])
filter_words.update(["body"])
filter_words.update(["bodyblow"])
filter_words.update(["bona fides"])
filter_words.update(["book"])
filter_words.update(["book death"])
filter_words.update(["boom"])
filter_words.update(["boon"])
filter_words.update(["boost"])
filter_words.update(["boot"])
filter_words.update(["bothpolicies"])
filter_words.update(["bottom"])
filter_words.update(["boy"])
filter_words.update(["branch"])
filter_words.update(["branch appointment"])
filter_words.update(["breadth"])
filter_words.update(["breakdown"])
filter_words.update(["breakneck pace"])
filter_words.update(["breakthrough"])
filter_words.update(["bridge"])
filter_words.update(["briefing"])
filter_words.update(["brigade"])
filter_words.update(["brink"])
filter_words.update(["brother"])
filter_words.update(["browsing"])
filter_words.update(["builder"])
filter_words.update(["building"])
filter_words.update(["building"])
filter_words.update(["building"])
filter_words.update(["building hospital"])
filter_words.update(["buildup"])
filter_words.update(["bulk"])
filter_words.update(["bulwark"])
filter_words.update(["burden"])
filter_words.update(["bush"])
filter_words.update(["business dealing"])
filter_words.update(["business tie"])
filter_words.update(["cabinet agency"])
filter_words.update(["call"])
filter_words.update(["call"])
filter_words.update(["camera"])
filter_words.update(["camp david"])
filter_words.update(["campaign pledge"])
filter_words.update(["campaign trail"])
filter_words.update(["campaignand"])
filter_words.update(["canada"])
filter_words.update(["cancel"])
filter_words.update(["capability"])
filter_words.update(["capacity"])
filter_words.update(["capital"])
filter_words.update(["capital spending"])
filter_words.update(["capitol hill"])
filter_words.update(["car"])
filter_words.update(["car"])
filter_words.update(["carbon"])
filter_words.update(["card"])
filter_words.update(["care"])
filter_words.update(["careerist"])
filter_words.update(["cascade"])
filter_words.update(["case"])
filter_words.update(["case study"])
filter_words.update(["cash"])
filter_words.update(["casualty"])
filter_words.update(["category"])
filter_words.update(["cause"])
filter_words.update(["cause"])
filter_words.update(["celebration"])
filter_words.update(["census"])
filter_words.update(["cent"])
filter_words.update(["center"])
filter_words.update(["centerpiece"])
filter_words.update(["ceo"])
filter_words.update(["certain washington politician"])
filter_words.update(["chain migration"])
filter_words.update(["chair"])
filter_words.update(["chairman"])
filter_words.update(["challenge"])
filter_words.update(["challengeor"])
filter_words.update(["chamber"])
filter_words.update(["champion"])
filter_words.update(["chance"])
filter_words.update(["chance"])
filter_words.update(["changehas"])
filter_words.update(["chaos"])
filter_words.update(["character"])
filter_words.update(["characterization"])
filter_words.update(["charge"])
filter_words.update(["charles"])
filter_words.update(["chart"])
filter_words.update(["check"])
filter_words.update(["cheer"])
filter_words.update(["chicago"])
filter_words.update(["chicago thursday"])
filter_words.update(["chief"])
filter_words.update(["child"])
filter_words.update(["chip"])
filter_words.update(["chocolate cake"])
filter_words.update(["choice"])
filter_words.update(["church"])
filter_words.update(["circle"])
filter_words.update(["circuit"])
filter_words.update(["circumstance"])
filter_words.update(["city center"])
filter_words.update(["civilian"])
filter_words.update(["claim"])
filter_words.update(["clarification"])
filter_words.update(["class"])
filter_words.update(["clay foot"])
filter_words.update(["client"])
filter_words.update(["closer"])
filter_words.update(["closing"])
filter_words.update(["closure"])
filter_words.update(["club"])
filter_words.update(["coalition"])
filter_words.update(["coffer"])
filter_words.update(["coherent"])
filter_words.update(["cohort"])
filter_words.update(["collaboration"])
filter_words.update(["collapse"])
filter_words.update(["collar job"])
filter_words.update(["colleague"])
filter_words.update(["college"])
filter_words.update(["college town"])
filter_words.update(["color"])
filter_words.update(["columbia university center"])
filter_words.update(["combination"])
filter_words.update(["comfort zone"])
filter_words.update(["comforter"])
filter_words.update(["command"])
filter_words.update(["comment"])
filter_words.update(["commentator"])
filter_words.update(["commitment"])
filter_words.update(["committee"])
filter_words.update(["committee chairman"])
filter_words.update(["committee meet today"])
filter_words.update(["commonwealth"])
filter_words.update(["community"])
filter_words.update(["comparison"])
filter_words.update(["compassion"])
filter_words.update(["competition"])
filter_words.update(["competitiveness"])
filter_words.update(["competitor"])
filter_words.update(["complaint"])
filter_words.update(["complete data"])
filter_words.update(["completion"])
filter_words.update(["complexity"])
filter_words.update(["compliance"])
filter_words.update(["compromise"])
filter_words.update(["concentration"])
filter_words.update(["concept"])
filter_words.update(["concern"])
filter_words.update(["concert"])
filter_words.update(["concession"])
filter_words.update(["conciliation"])
filter_words.update(["conclusion"])
filter_words.update(["conclusion"])
filter_words.update(["concrete"])
filter_words.update(["concrete detail"])
filter_words.update(["condition"])
filter_words.update(["conference"])
filter_words.update(["conference call"])
filter_words.update(["confidence boost"])
filter_words.update(["confirm"])
filter_words.update(["confirmation hearing"])
filter_words.update(["confrontational"])
filter_words.update(["confusion"])
filter_words.update(["congratulatory"])
filter_words.update(["congressman"])
filter_words.update(["connection"])
filter_words.update(["consent"])
filter_words.update(["consequence"])
filter_words.update(["conservative"])
filter_words.update(["consideration"])
filter_words.update(["consisting"])
filter_words.update(["conspiracy"])
filter_words.update(["constancy"])
filter_words.update(["constitution"])
filter_words.update(["constitutionality"])
filter_words.update(["constraint"])
filter_words.update(["construct"])
filter_words.update(["construction"])
filter_words.update(["consultation"])
filter_words.update(["consumer"])
filter_words.update(["consumption"])
filter_words.update(["contact"])
filter_words.update(["contempt"])
filter_words.update(["content"])
filter_words.update(["context"])
filter_words.update(["contingent"])
filter_words.update(["contract"])
filter_words.update(["contrary"])
filter_words.update(["contribution"])
filter_words.update(["controversy"])
filter_words.update(["convention"])
filter_words.update(["conversation"])
filter_words.update(["cooky"])
filter_words.update(["cooperation"])
filter_words.update(["cooperation"])
filter_words.update(["coordination"])
filter_words.update(["copy"])
filter_words.update(["core"])
filter_words.update(["core element"])
filter_words.update(["core objective"])
filter_words.update(["core purpose"])
filter_words.update(["core set"])
filter_words.update(["cornerstone"])
filter_words.update(["corporation"])
filter_words.update(["correctness"])
filter_words.update(["corruption"])
filter_words.update(["cost"])
filter_words.update(["council"])
filter_words.update(["counsel"])
filter_words.update(["count"])
filter_words.update(["counterpart"])
filter_words.update(["country"])
filter_words.update(["country ambassador"])
filter_words.update(["country highway"])
filter_words.update(["country stance"])
filter_words.update(["coup"])
filter_words.update(["couple"])
filter_words.update(["couple decade"])
filter_words.update(["couple week"])
filter_words.update(["course"])
filter_words.update(["court filing"])
filter_words.update(["court system"])
filter_words.update(["cousin"])
filter_words.update(["coverage"])
filter_words.update(["cr"])
filter_words.update(["crash"])
filter_words.update(["cream"])
filter_words.update(["create"])
filter_words.update(["creator"])
filter_words.update(["credence"])
filter_words.update(["credibility"])
filter_words.update(["credit"])
filter_words.update(["crime"])
filter_words.update(["criminal"])
filter_words.update(["crisis"])
filter_words.update(["criterion"])
filter_words.update(["critic"])
filter_words.update(["criticism"])
filter_words.update(["crosshairs"])
filter_words.update(["crossing"])
filter_words.update(["crowd"])
filter_words.update(["cruise"])
filter_words.update(["crust"])
filter_words.update(["crux"])
filter_words.update(["culture"])
filter_words.update(["cure"])
filter_words.update(["curiosity"])
filter_words.update(["currency manipulator"])
filter_words.update(["cusp"])
filter_words.update(["custom"])
filter_words.update(["cut"])
filter_words.update(["cut"])
filter_words.update(["cyber"])
filter_words.update(["cycle"])
filter_words.update(["dallek"])
filter_words.update(["damn point"])
filter_words.update(["dark cloud lifting"])
filter_words.update(["data"])
filter_words.update(["data show"])
filter_words.update(["date"])
filter_words.update(["daughter"])
filter_words.update(["day address"])
filter_words.update(["deadline"])
filter_words.update(["deal"])
filter_words.update(["dealmaking"])
filter_words.update(["death"])
filter_words.update(["death toll"])
filter_words.update(["debate"])
filter_words.update(["decade"])
filter_words.update(["december phone"])
filter_words.update(["decency"])
filter_words.update(["decision"])
filter_words.update(["decision isnt"])
filter_words.update(["decision mr trump"])
filter_words.update(["decisionmaking"])
filter_words.update(["deck"])
filter_words.update(["declaration"])
filter_words.update(["decline"])
filter_words.update(["deductible"])
filter_words.update(["deduction"])
filter_words.update(["deed"])
filter_words.update(["deep"])
filter_words.update(["defeat"])
filter_words.update(["defeat"])
filter_words.update(["defense"])
filter_words.update(["defense department"])
filter_words.update(["deference"])
filter_words.update(["degree"])
filter_words.update(["delivery"])
filter_words.update(["delivery system"])
filter_words.update(["demand"])
filter_words.update(["demeaning"])
filter_words.update(["democracy"])
filter_words.update(["demonstration"])
filter_words.update(["department"])
filter_words.update(["departure"])
filter_words.update(["departure"])
filter_words.update(["dependence"])
filter_words.update(["depends"])
filter_words.update(["deployment"])
filter_words.update(["depth"])
filter_words.update(["description"])
filter_words.update(["designation time"])
filter_words.update(["desire"])
filter_words.update(["desk"])
filter_words.update(["desolate"])
filter_words.update(["destination"])
filter_words.update(["destruction"])
filter_words.update(["detail"])
filter_words.update(["detention"])
filter_words.update(["determination"])
filter_words.update(["detroit"])
filter_words.update(["device"])
filter_words.update(["dhs"])
filter_words.update(["diatribe"])
filter_words.update(["didnt"])
filter_words.update(["difference"])
filter_words.update(["difference"])
filter_words.update(["difficulty"])
filter_words.update(["dill"])
filter_words.update(["dime"])
filter_words.update(["dining room"])
filter_words.update(["dinner"])
filter_words.update(["direction"])
filter_words.update(["directive"])
filter_words.update(["director"])
filter_words.update(["dirty"])
filter_words.update(["disadvantage"])
filter_words.update(["discourse"])
filter_words.update(["discretion"])
filter_words.update(["discussion"])
filter_words.update(["disease"])
filter_words.update(["dismay"])
filter_words.update(["dismissal"])
filter_words.update(["display"])
filter_words.update(["disruption"])
filter_words.update(["disruptive"])
filter_words.update(["distance"])
filter_words.update(["distinct"])
filter_words.update(["distraction"])
filter_words.update(["district"])
filter_words.update(["district court"])
filter_words.update(["diversity"])
filter_words.update(["divide"])
filter_words.update(["division"])
filter_words.update(["doctrine"])
filter_words.update(["document"])
filter_words.update(["doesnt"])
filter_words.update(["dollar"])
filter_words.update(["donor"])
filter_words.update(["dont"])
filter_words.update(["door"])
filter_words.update(["door friday"])
filter_words.update(["door shut"])
filter_words.update(["doozy"])
filter_words.update(["dossier"])
filter_words.update(["doubt"])
filter_words.update(["doubter"])
filter_words.update(["dozen"])
filter_words.update(["dozen attorney"])
filter_words.update(["draft"])
filter_words.update(["drafting"])
filter_words.update(["drag"])
filter_words.update(["drama"])
filter_words.update(["drawback"])
filter_words.update(["drinking"])
filter_words.update(["driver"])
filter_words.update(["drop"])
filter_words.update(["duh"])
filter_words.update(["duration"])
filter_words.update(["dust"])
filter_words.update(["dustup"])
filter_words.update(["duty"])
filter_words.update(["east"])
filter_words.update(["economics"])
filter_words.update(["editor"])
filter_words.update(["education fund"])
filter_words.update(["effect"])
filter_words.update(["effective"])
filter_words.update(["effectiveness"])
filter_words.update(["effort"])
filter_words.update(["eg"])
filter_words.update(["el paso"])
filter_words.update(["el salvador"])
filter_words.update(["element"])
filter_words.update(["elevation"])
filter_words.update(["elimination"])
filter_words.update(["elite"])
filter_words.update(["email"])
filter_words.update(["emerge"])
filter_words.update(["emergency stay"])
filter_words.update(["emphasis"])
filter_words.update(["employee"])
filter_words.update(["employee"])
filter_words.update(["employment"])
filter_words.update(["enacts"])
filter_words.update(["encouraging"])
filter_words.update(["end"])
filter_words.update(["endangered specie act"])
filter_words.update(["endowed chair"])
filter_words.update(["enemy"])
filter_words.update(["engagement"])
filter_words.update(["engine"])
filter_words.update(["engineering"])
filter_words.update(["enrollment"])
filter_words.update(["enthusiasm"])
filter_words.update(["entity"])
filter_words.update(["entourage"])
filter_words.update(["entry"])
filter_words.update(["entry"])
filter_words.update(["environment"])
filter_words.update(["epidemic"])
filter_words.update(["episode"])
filter_words.update(["equality"])
filter_words.update(["equity investor"])
filter_words.update(["equivalent"])
filter_words.update(["era"])
filter_words.update(["eric"])
filter_words.update(["establishment republican"])
filter_words.update(["estate"])
filter_words.update(["estate magnate"])
filter_words.update(["estimate"])
filter_words.update(["ethic"])
filter_words.update(["ethic official"])
filter_words.update(["eve"])
filter_words.update(["event"])
filter_words.update(["everybody"])
filter_words.update(["everybody"])
filter_words.update(["everyone"])
filter_words.update(["everyone regardless"])
filter_words.update(["everything"])
filter_words.update(["evidence"])
filter_words.update(["evolution"])
filter_words.update(["examination"])
filter_words.update(["example"])
filter_words.update(["exception"])
filter_words.update(["exchange"])
filter_words.update(["executive"])
filter_words.update(["executive"])
filter_words.update(["executive action"])
filter_words.update(["executive branch"])
filter_words.update(["executive secretary"])
filter_words.update(["exercise"])
filter_words.update(["exhaustion"])
filter_words.update(["existence"])
filter_words.update(["exit"])
filter_words.update(["exit poll"])
filter_words.update(["expansion"])
filter_words.update(["expectation"])
filter_words.update(["expense"])
filter_words.update(["experience"])
filter_words.update(["expert"])
filter_words.update(["expiration"])
filter_words.update(["explanation"])
filter_words.update(["exploit"])
filter_words.update(["exploration"])
filter_words.update(["expose"])
filter_words.update(["expression"])
filter_words.update(["extent"])
filter_words.update(["exuberance"])
filter_words.update(["eye"])
filter_words.update(["eye"])
filter_words.update(["facade"])
filter_words.update(["face"])
filter_words.update(["face value"])
filter_words.update(["facility"])
filter_words.update(["faction"])
filter_words.update(["factor"])
filter_words.update(["factory"])
filter_words.update(["failing"])
filter_words.update(["failure"])
filter_words.update(["faith"])
filter_words.update(["fake"])
filter_words.update(["fall"])
filter_words.update(["fall"])
filter_words.update(["fallen american"])
filter_words.update(["fallout"])
filter_words.update(["family perspective"])
filter_words.update(["family trust"])
filter_words.update(["fan"])
filter_words.update(["fannie"])
filter_words.update(["fashion"])
filter_words.update(["fault"])
filter_words.update(["favor"])
filter_words.update(["favorability"])
filter_words.update(["favorite"])
filter_words.update(["favoritism"])
filter_words.update(["fear"])
filter_words.update(["feat"])
filter_words.update(["feature"])
filter_words.update(["fed"])
filter_words.update(["federal"])
filter_words.update(["federation"])
filter_words.update(["fee"])
filter_words.update(["feel"])
filter_words.update(["feeling"])
filter_words.update(["fellow"])
filter_words.update(["felony"])
filter_words.update(["fence"])
filter_words.update(["fide"])
filter_words.update(["field"])
filter_words.update(["fifth"])
filter_words.update(["fifth third"])
filter_words.update(["fight"])
filter_words.update(["fighter jet"])
filter_words.update(["figure"])
filter_words.update(["filer"])
filter_words.update(["finance"])
filter_words.update(["financing"])
filter_words.update(["finding"])
filter_words.update(["fingerprinting"])
filter_words.update(["fire"])
filter_words.update(["firm"])
filter_words.update(["first lady"])
filter_words.update(["fix"])
filter_words.update(["flag"])
filter_words.update(["flake"])
filter_words.update(["flame"])
filter_words.update(["flank"])
filter_words.update(["flight"])
filter_words.update(["flinch"])
filter_words.update(["floor"])
filter_words.update(["floor schedule"])
filter_words.update(["floor time"])
filter_words.update(["flow"])
filter_words.update(["flux"])
filter_words.update(["fly"])
filter_words.update(["flynn"])
filter_words.update(["focus"])
filter_words.update(["folk"])
filter_words.update(["food"])
filter_words.update(["foot"])
filter_words.update(["football player"])
filter_words.update(["forefront"])
filter_words.update(["foreign ministry"])
filter_words.update(["foremost"])
filter_words.update(["form"])
filter_words.update(["format"])
filter_words.update(["formula"])
filter_words.update(["forth"])
filter_words.update(["fortune"])
filter_words.update(["fourth"])
filter_words.update(["fraction"])
filter_words.update(["fracturing"])
filter_words.update(["framework"])
filter_words.update(["france"])
filter_words.update(["freedom"])
filter_words.update(["freeze"])
filter_words.update(["friction"])
filter_words.update(["friday afternoon trump"])
filter_words.update(["friday morning"])
filter_words.update(["friday night"])
filter_words.update(["friend"])
filter_words.update(["front"])
filter_words.update(["fruit"])
filter_words.update(["frustration"])
filter_words.update(["fund"])
filter_words.update(["funding"])
filter_words.update(["funding project"])
filter_words.update(["fundraising"])
filter_words.update(["future"])
filter_words.update(["gain"])
filter_words.update(["game"])
filter_words.update(["garbage"])
filter_words.update(["garland"])
filter_words.update(["gathering"])
filter_words.update(["gauge"])
filter_words.update(["gay"])
filter_words.update(["general"])
filter_words.update(["general agreement"])
filter_words.update(["generation"])
filter_words.update(["generator"])
filter_words.update(["geography"])
filter_words.update(["geography limitation"])
filter_words.update(["geolocation"])
filter_words.update(["geopolitics"])
filter_words.update(["germane"])
filter_words.update(["gerrymander"])
filter_words.update(["gerrymandering effort"])
filter_words.update(["gesture"])
filter_words.update(["get"])
filter_words.update(["gift"])
filter_words.update(["giveaway"])
filter_words.update(["glass"])
filter_words.update(["glimpse"])
filter_words.update(["goal"])
filter_words.update(["gobetween"])
filter_words.update(["god bless"])
filter_words.update(["god bless america"])
filter_words.update(["gold"])
filter_words.update(["golf course"])
filter_words.update(["good"])
filter_words.update(["goodness"])
filter_words.update(["government"])
filter_words.update(["government effort"])
filter_words.update(["government email"])
filter_words.update(["government service"])
filter_words.update(["governmentshould"])
filter_words.update(["grab"])
filter_words.update(["grandchild"])
filter_words.update(["grandparent"])
filter_words.update(["grant"])
filter_words.update(["grasp"])
filter_words.update(["great move"])
filter_words.update(["greeting"])
filter_words.update(["grid"])
filter_words.update(["gridlock"])
filter_words.update(["grief"])
filter_words.update(["grip"])
filter_words.update(["ground"])
filter_words.update(["groundbreaking speech"])
filter_words.update(["group"])
filter_words.update(["growth"])
filter_words.update(["gru"])
filter_words.update(["gsa"])
filter_words.update(["guard"])
filter_words.update(["guardian"])
filter_words.update(["guidance"])
filter_words.update(["guideline"])
filter_words.update(["gulf"])
filter_words.update(["gut"])
filter_words.update(["guy"])
filter_words.update(["h2a visa"])
filter_words.update(["hacker"])
filter_words.update(["half"])
filter_words.update(["half decade"])
filter_words.update(["halt"])
filter_words.update(["halting"])
filter_words.update(["hamburg"])
filter_words.update(["hand"])
filter_words.update(["handful"])
filter_words.update(["handling"])
filter_words.update(["happen"])
filter_words.update(["happiness"])
filter_words.update(["hardball"])
filter_words.update(["harder"])
filter_words.update(["hardline"])
filter_words.update(["hardline position"])
filter_words.update(["hardliner"])
filter_words.update(["hardliners"])
filter_words.update(["hbr"])
filter_words.update(["head"])
filter_words.update(["health"])
filter_words.update(["health information"])
filter_words.update(["hearing"])
filter_words.update(["heart"])
filter_words.update(["helicopter"])
filter_words.update(["hell"])
filter_words.update(["hell use"])
filter_words.update(["hellbent"])
filter_words.update(["help"])
filter_words.update(["henry brady"])
filter_words.update(["heritage"])
filter_words.update(["hidden"])
filter_words.update(["high"])
filter_words.update(["highway"])
filter_words.update(["hill"])
filter_words.update(["hindrance"])
filter_words.update(["hint"])
filter_words.update(["hire"])
filter_words.update(["hiring"])
filter_words.update(["historian"])
filter_words.update(["historic contrast"])
filter_words.update(["history"])
filter_words.update(["history show"])
filter_words.update(["hit"])
filter_words.update(["hit job"])
filter_words.update(["hitler"])
filter_words.update(["hive"])
filter_words.update(["hoax"])
filter_words.update(["hold"])
filter_words.update(["holder"])
filter_words.update(["hole"])
filter_words.update(["hollow"])
filter_words.update(["hollywood"])
filter_words.update(["hollywood producer"])
filter_words.update(["holtzeakin"])
filter_words.update(["home"])
filter_words.update(["home"])
filter_words.update(["home community"])
filter_words.update(["homeless veteran"])
filter_words.update(["homeowner"])
filter_words.update(["honesty"])
filter_words.update(["honor"])
filter_words.update(["hope"])
filter_words.update(["horizon investment"])
filter_words.update(["hostility"])
filter_words.update(["hour lunch"])
filter_words.update(["house"])
filter_words.update(["house committee"])
filter_words.update(["household status"])
filter_words.update(["houston"])
filter_words.update(["huddle"])
filter_words.update(["hum"])
filter_words.update(["hundred"])
filter_words.update(["huntington"])
filter_words.update(["husband"])
filter_words.update(["hut"])
filter_words.update(["ibm"])
filter_words.update(["ic"])
filter_words.update(["id"])
filter_words.update(["id program"])
filter_words.update(["idea"])
filter_words.update(["ideologue"])
filter_words.update(["ideology"])
filter_words.update(["iea"])
filter_words.update(["iers director"])
filter_words.update(["iers finding"])
filter_words.update(["ignorance"])
filter_words.update(["illiquidity"])
filter_words.update(["im confident"])
filter_words.update(["imagery"])
filter_words.update(["imagination"])
filter_words.update(["immediate"])
filter_words.update(["impact"])
filter_words.update(["impasse"])
filter_words.update(["impeach trump"])
filter_words.update(["impeachment"])
filter_words.update(["implementation"])
filter_words.update(["implication"])
filter_words.update(["importance"])
filter_words.update(["impression"])
filter_words.update(["improvement"])
filter_words.update(["inability"])
filter_words.update(["incarnation"])
filter_words.update(["incentive"])
filter_words.update(["inch"])
filter_words.update(["incident"])
filter_words.update(["inclusion"])
filter_words.update(["inclusiveness"])
filter_words.update(["income"])
filter_words.update(["income sent"])
filter_words.update(["increase"])
filter_words.update(["independence day"])
filter_words.update(["independent"])
filter_words.update(["indiana"])
filter_words.update(["indianapolis"])
filter_words.update(["indianapolis factory"])
filter_words.update(["indication"])
filter_words.update(["indicator"])
filter_words.update(["indifference"])
filter_words.update(["individual"])
filter_words.update(["industry"])
filter_words.update(["inefficiency"])
filter_words.update(["inefficient"])
filter_words.update(["infighting"])
filter_words.update(["infiltration"])
filter_words.update(["inflation"])
filter_words.update(["influence"])
filter_words.update(["influence"])
filter_words.update(["information"])
filter_words.update(["information age"])
filter_words.update(["information flow"])
filter_words.update(["information war"])
filter_words.update(["infrastructure act"])
filter_words.update(["infrastructure investment"])
filter_words.update(["infrastructure need"])
filter_words.update(["infrastructure permitting decision"])
filter_words.update(["infrastructure policy bank"])
filter_words.update(["infrastructure project"])
filter_words.update(["infrastructure spending crisis"])
filter_words.update(["infusion"])
filter_words.update(["initiative"])
filter_words.update(["injury"])
filter_words.update(["innovation"])
filter_words.update(["inquiry"])
filter_words.update(["insight"])
filter_words.update(["instance"])
filter_words.update(["institute"])
filter_words.update(["institution"])
filter_words.update(["institution"])
filter_words.update(["instruction"])
filter_words.update(["instructor"])
filter_words.update(["insurance"])
filter_words.update(["insurance company"])
filter_words.update(["insurer"])
filter_words.update(["intake session"])
filter_words.update(["integrity"])
filter_words.update(["intelligence"])
filter_words.update(["intent"])
filter_words.update(["intention"])
filter_words.update(["intention"])
filter_words.update(["interaction"])
filter_words.update(["interest"])
filter_words.update(["interest collusion"])
filter_words.update(["interest loophole"])
filter_words.update(["interior"])
filter_words.update(["internal revenue service"])
filter_words.update(["international boundary"])
filter_words.update(["international study"])
filter_words.update(["internationalism"])
filter_words.update(["internet"])
filter_words.update(["internet service provider"])
filter_words.update(["interpretation"])
filter_words.update(["interview"])
filter_words.update(["interview below"])
filter_words.update(["intractability"])
filter_words.update(["invest"])
filter_words.update(["investing"])
filter_words.update(["investment"])
filter_words.update(["investment company"])
filter_words.update(["investment growth"])
filter_words.update(["investment mr kushner"])
filter_words.update(["investment office"])
filter_words.update(["investment strategist"])
filter_words.update(["investor"])
filter_words.update(["invitation"])
filter_words.update(["invite"])
filter_words.update(["involvement"])
filter_words.update(["iowa"])
filter_words.update(["iowa sen chuck grassley"])
filter_words.update(["ire"])
filter_words.update(["irs control"])
filter_words.update(["irs recruiter"])
filter_words.update(["irs rule"])
filter_words.update(["irvine"])
filter_words.update(["isi"])
filter_words.update(["island"])
filter_words.update(["island"])
filter_words.update(["isp"])
filter_words.update(["isps"])
filter_words.update(["israeli delegation"])
filter_words.update(["issue"])
filter_words.update(["iteration"])
filter_words.update(["ivanka trump product"])
filter_words.update(["j d gordon"])
filter_words.update(["james clapper"])
filter_words.update(["james rockas"])
filter_words.update(["jane nakano"])
filter_words.update(["january report"])
filter_words.update(["jeffrey korzenik"])
filter_words.update(["jennifer hing"])
filter_words.update(["jetswhich"])
filter_words.update(["jew"])
filter_words.update(["john delury"])
filter_words.update(["john macomber"])
filter_words.update(["johnson reelection chance"])
filter_words.update(["jonathan turley"])
filter_words.update(["joo"])
filter_words.update(["joseph e schmitz"])
filter_words.update(["journal"])
filter_words.update(["joy"])
filter_words.update(["jpmorgan"])
filter_words.update(["judge merrick garland"])
filter_words.update(["judge saturday"])
filter_words.update(["judgment"])
filter_words.update(["jurisdiction"])
filter_words.update(["just day"])
filter_words.update(["just hour"])
filter_words.update(["kaiser poll"])
filter_words.update(["kalugin"])
filter_words.update(["karen"])
filter_words.update(["keith kellogg"])
filter_words.update(["kelly"])
filter_words.update(["kevin"])
filter_words.update(["key"])
filter_words.update(["kind"])
filter_words.update(["kitchen cabinet likewise"])
filter_words.update(["know"])
filter_words.update(["knowledge"])
filter_words.update(["kushner"])
filter_words.update(["kyle pope"])
filter_words.update(["la vega"])
filter_words.update(["la vega labor dispute"])
filter_words.update(["label"])
filter_words.update(["labor"])
filter_words.update(["lack"])
filter_words.update(["lack"])
filter_words.update(["lady"])
filter_words.update(["lake tahoe"])
filter_words.update(["land"])
filter_words.update(["land use"])
filter_words.update(["landfall"])
filter_words.update(["landing"])
filter_words.update(["landowner"])
filter_words.update(["language"])
filter_words.update(["lapdog"])
filter_words.update(["latino"])
filter_words.update(["latinoheavy electorate"])
filter_words.update(["launchpad"])
filter_words.update(["laurence tribe"])
filter_words.update(["law"])
filter_words.update(["lawmaker"])
filter_words.update(["lawsuit"])
filter_words.update(["lawyer"])
filter_words.update(["layer"])
filter_words.update(["lead"])
filter_words.update(["leader"])
filter_words.update(["leadership"])
filter_words.update(["leadership ability"])
filter_words.update(["leadership role"])
filter_words.update(["leadership strategy"])
filter_words.update(["leadup"])
filter_words.update(["league"])
filter_words.update(["leaky"])
filter_words.update(["leap"])
filter_words.update(["lease"])
filter_words.update(["lectern"])
filter_words.update(["lecturer"])
filter_words.update(["lee drutman"])
filter_words.update(["leery"])
filter_words.update(["legislation"])
filter_words.update(["len burman"])
filter_words.update(["length"])
filter_words.update(["leon"])
filter_words.update(["leon charles"])
filter_words.update(["letter"])
filter_words.update(["level"])
filter_words.update(["leverage"])
filter_words.update(["li"])
filter_words.update(["li shuo"])
filter_words.update(["liaoning academy"])
filter_words.update(["liberal"])
filter_words.update(["liberty"])
filter_words.update(["lie"])
filter_words.update(["lieu"])
filter_words.update(["life"])
filter_words.update(["lifetime"])
filter_words.update(["light"])
filter_words.update(["like"])
filter_words.update(["likelihood"])
filter_words.update(["limbo"])
filter_words.update(["limit"])
filter_words.update(["limitation"])
filter_words.update(["limousine"])
filter_words.update(["line"])
filter_words.update(["lingling mu"])
filter_words.update(["link"])
filter_words.update(["list"])
filter_words.update(["litany"])
filter_words.update(["liter"])
filter_words.update(["load box"])
filter_words.update(["loan"])
filter_words.update(["lobbyist"])
filter_words.update(["localization"])
filter_words.update(["location"])
filter_words.update(["locker room"])
filter_words.update(["lofgren"])
filter_words.update(["logistics"])
filter_words.update(["longstanding"])
filter_words.update(["look"])
filter_words.update(["loophole"])
filter_words.update(["loosening"])
filter_words.update(["los angeles"])
filter_words.update(["los angeles garcetti"])
filter_words.update(["los angeles mayor eric garcetti"])
filter_words.update(["loss"])
filter_words.update(["loss"])
filter_words.update(["lot"])
filter_words.update(["louisiana state university"])
filter_words.update(["love"])
filter_words.update(["low"])
filter_words.update(["loyal"])
filter_words.update(["loyalty"])
filter_words.update(["lunch"])
filter_words.update(["lyft"])
filter_words.update(["machine"])
filter_words.update(["machine case"])
filter_words.update(["macomber"])
filter_words.update(["maga"])
filter_words.update(["main street"])
filter_words.update(["maine"])
filter_words.update(["maintenance"])
filter_words.update(["majority"])
filter_words.update(["makeup flip"])
filter_words.update(["man"])
filter_words.update(["man"])
filter_words.update(["management"])
filter_words.update(["manager"])
filter_words.update(["mandate"])
filter_words.update(["maneuver"])
filter_words.update(["manifestation"])
filter_words.update(["manufacturer carrier"])
filter_words.update(["map"])
filter_words.update(["marble jarring"])
filter_words.update(["march order"])
filter_words.update(["margin"])
filter_words.update(["mark"])
filter_words.update(["market"])
filter_words.update(["marketer"])
filter_words.update(["marketing association"])
filter_words.update(["marketplace"])
filter_words.update(["martin b"])
filter_words.update(["mass"])
filter_words.update(["mass medium"])
filter_words.update(["match"])
filter_words.update(["material"])
filter_words.update(["material cost"])
filter_words.update(["maternity"])
filter_words.update(["math"])
filter_words.update(["matter"])
filter_words.update(["mayday"])
filter_words.update(["mayor rahm emanuel"])
filter_words.update(["meadow"])
filter_words.update(["meadow"])
filter_words.update(["meal"])
filter_words.update(["mean"])
filter_words.update(["meant"])
filter_words.update(["meantime"])
filter_words.update(["measure"])
filter_words.update(["medal"])
filter_words.update(["medium"])
filter_words.update(["medium bias"])
filter_words.update(["medium coverage"])
filter_words.update(["medium like"])
filter_words.update(["medium mention"])
filter_words.update(["meet"])
filter_words.update(["meeting"])
filter_words.update(["meeting thursday morning"])
filter_words.update(["melaniaTrump"])
filter_words.update(["member"])
filter_words.update(["men"])
filter_words.update(["mention"])
filter_words.update(["mention navigator"])
filter_words.update(["merit"])
filter_words.update(["mess"])
filter_words.update(["message"])
filter_words.update(["messaging"])
filter_words.update(["method"])
filter_words.update(["mich"])
filter_words.update(["michael jordan"])
filter_words.update(["michigan"])
filter_words.update(["microphone"])
filter_words.update(["midnight"])
filter_words.update(["midst"])
filter_words.update(["midterm"])
filter_words.update(["midwest"])
filter_words.update(["migration"])
filter_words.update(["mikhail kulagin"])
filter_words.update(["mile"])
filter_words.update(["milesplus"])
filter_words.update(["million"])
filter_words.update(["mind"])
filter_words.update(["minefield"])
filter_words.update(["miner"])
filter_words.update(["minimum"])
filter_words.update(["ministry"])
filter_words.update(["minority"])
filter_words.update(["minute meeting"])
filter_words.update(["misdemeanor"])
filter_words.update(["misinformation"])
filter_words.update(["mismanagement"])
filter_words.update(["misread"])
filter_words.update(["mitt romney"])
filter_words.update(["mix"])
filter_words.update(["mode"])
filter_words.update(["model"])
filter_words.update(["modernization"])
filter_words.update(["modernization program"])
filter_words.update(["moment"])
filter_words.update(["momentum"])
filter_words.update(["Monday"])
filter_words.update(["money"])
filter_words.update(["moniker"])
filter_words.update(["monitoring"])
filter_words.update(["monument"])
filter_words.update(["moody"])
filter_words.update(["moody analytics"])
filter_words.update(["moratorium"])
filter_words.update(["mother"])
filter_words.update(["motif"])
filter_words.update(["motion"])
filter_words.update(["motive"])
filter_words.update(["mountain"])
filter_words.update(["move"])
filter_words.update(["mr icahns"])
filter_words.update(["mr kalman"])
filter_words.update(["mr kim"])
filter_words.update(["mr korzenik"])
filter_words.update(["mr penny"])
filter_words.update(["mr ross decision"])
filter_words.update(["mr ross russia tie"])
filter_words.update(["mr spicer"])
filter_words.update(["mr taraghi"])
filter_words.update(["mr trump assertion"])
filter_words.update(["mr trump soninlaw"])
filter_words.update(["mr trump ultimatum"])
filter_words.update(["mr xi government"])
filter_words.update(["mr xi reelection"])
filter_words.update(["mrs trump"])
filter_words.update(["ms canter"])
filter_words.update(["ms cliffords camp"])
filter_words.update(["ms daniel"])
filter_words.update(["ms devos"])
filter_words.update(["mueller seek white house document"])
filter_words.update(["multibillion dollar plan"])
filter_words.update(["multilateralism"])
filter_words.update(["multinationals"])
filter_words.update(["municipality"])
filter_words.update(["myriad industry"])
filter_words.update(["myron ebell"])
filter_words.update(["myth"])
filter_words.update(["nader karimi joni"])
filter_words.update(["name"])
filter_words.update(["narrative"])
filter_words.update(["nascent union"])
filter_words.update(["nation"])
filter_words.update(["nation bigcity mayor"])
filter_words.update(["national"])
filter_words.update(["national"])
filter_words.update(["national academy"])
filter_words.update(["national anthem"])
filter_words.update(["national association"])
filter_words.update(["national committee"])
filter_words.update(["national economic council director gary cohn"])
filter_words.update(["national federation"])
filter_words.update(["national historic preservation act"])
filter_words.update(["national intelligence"])
filter_words.update(["national park service"])
filter_words.update(["national press club president thomas burr"])
filter_words.update(["national rifle association"])
filter_words.update(["national security act"])
filter_words.update(["national security adviser hr"])
filter_words.update(["national security decision directive"])
filter_words.update(["national war college"])
filter_words.update(["nationalism"])
filter_words.update(["nato"])
filter_words.update(["nature"])
filter_words.update(["navigator"])
filter_words.update(["navigator investment"])
filter_words.update(["nazi germany"])
filter_words.update(["nazi regime"])
filter_words.update(["nba"])
filter_words.update(["nba superstar steph curry"])
filter_words.update(["nbc thursday"])
filter_words.update(["nbcs meet"])
filter_words.update(["nearlock"])
filter_words.update(["need"])
filter_words.update(["needle"])
filter_words.update(["negotiation"])
filter_words.update(["negotiation technique"])
filter_words.update(["neighborhood"])
filter_words.update(["neophyte"])
filter_words.update(["nesting doll"])
filter_words.update(["network"])
filter_words.update(["nevada"])
filter_words.update(["new america"])
filter_words.update(["new approach"])
filter_words.update(["new braunfels"])
filter_words.update(["new day"])
filter_words.update(["new hampshire"])
filter_words.update(["new haven"])
filter_words.update(["new jersey"])
filter_words.update(["new year"])
filter_words.update(["new york area"])
filter_words.update(["new york city mayor bill"])
filter_words.update(["new york guy"])
filter_words.update(["new york state"])
filter_words.update(["newcomer"])
filter_words.update(["nfl criticism president donald trump"])
filter_words.update(["nielsen"])
filter_words.update(["nigel farage"])
filter_words.update(["nightmare"])
filter_words.update(["nile gardiner"])
filter_words.update(["ninetyone"])
filter_words.update(["no deal"])
filter_words.update(["no loan"])
filter_words.update(["no nothing"])
filter_words.update(["nobody"])
filter_words.update(["nod"])
filter_words.update(["nominee"])
filter_words.update(["non grata"])
filter_words.update(["none"])
filter_words.update(["nonprofit"])
filter_words.update(["nonstarter"])
filter_words.update(["norm"])
filter_words.update(["north"])
filter_words.update(["north"])
filter_words.update(["north carolina state legislature"])
filter_words.update(["northeast"])
filter_words.update(["northeast asia"])
filter_words.update(["northrop grumman"])
filter_words.update(["notch"])
filter_words.update(["note"])
filter_words.update(["nothing"])
filter_words.update(["nothing damning"])
filter_words.update(["notice"])
filter_words.update(["notification"])
filter_words.update(["noting"])
filter_words.update(["november election"])
filter_words.update(["nseers"])
filter_words.update(["nsenga burton"])
filter_words.update(["nt"])
filter_words.update(["nuance"])
filter_words.update(["number"])
filter_words.update(["nunes"])
filter_words.update(["nursing home"])
filter_words.update(["oath"])
filter_words.update(["objective"])
filter_words.update(["observation"])
filter_words.update(["observer"])
filter_words.update(["obsession"])
filter_words.update(["obstacle"])
filter_words.update(["occurrence"])
filter_words.update(["oceana"])
filter_words.update(["octogenarian"])
filter_words.update(["oddity"])
filter_words.update(["odds"])
filter_words.update(["offense"])
filter_words.update(["offer"])
filter_words.update(["office"])
filter_words.update(["office building"])
filter_words.update(["office investigation"])
filter_words.update(["office tomorrow"])
filter_words.update(["officer"])
filter_words.update(["official"])
filter_words.update(["ohio congressman"])
filter_words.update(["oklahoma"])
filter_words.update(["old"])
filter_words.update(["old post office pavilion"])
filter_words.update(["oligarch hit"])
filter_words.update(["oligarch subject"])
filter_words.update(["omb"])
filter_words.update(["omb guidance"])
filter_words.update(["omission"])
filter_words.update(["one man"])
filter_words.update(["onefourth"])
filter_words.update(["opening"])
filter_words.update(["opening occur"])
filter_words.update(["opening shot"])
filter_words.update(["openness"])
filter_words.update(["operating fee"])
filter_words.update(["operation"])
filter_words.update(["operative"])
filter_words.update(["operator"])
filter_words.update(["opinion"])
filter_words.update(["opinion drop"])
filter_words.update(["opm"])
filter_words.update(["opponent"])
filter_words.update(["opponent"])
filter_words.update(["opportunity"])
filter_words.update(["opposite"])
filter_words.update(["opposition party muscle"])
filter_words.update(["opposition research firm fusion gps"])
filter_words.update(["oppression"])
filter_words.update(["optimism"])
filter_words.update(["option"])
filter_words.update(["orbit"])
filter_words.update(["order"])
filter_words.update(["order attempt"])
filter_words.update(["organization"])
filter_words.update(["organization"])
filter_words.update(["organization endeavor"])
filter_words.update(["ourso school"])
filter_words.update(["outcome"])
filter_words.update(["outcome"])
filter_words.update(["outdoor address"])
filter_words.update(["outgrowth"])
filter_words.update(["outlet"])
filter_words.update(["outline"])
filter_words.update(["output"])
filter_words.update(["oval"])
filter_words.update(["oval office"])
filter_words.update(["overflight"])
filter_words.update(["overhaul"])
filter_words.update(["overreach"])
filter_words.update(["overseer"])
filter_words.update(["owner"])
filter_words.update(["pa"])
filter_words.update(["pace"])
filter_words.update(["pacific"])
filter_words.update(["package"])
filter_words.update(["pact"])
filter_words.update(["page"])
filter_words.update(["pain"])
filter_words.update(["pair"])
filter_words.update(["palestine"])
filter_words.update(["panel"])
filter_words.update(["panel monday"])
filter_words.update(["paper"])
filter_words.update(["paperwork"])
filter_words.update(["paramount"])
filter_words.update(["parent"])
filter_words.update(["parent company"])
filter_words.update(["parenthood"])
filter_words.update(["paris"])
filter_words.update(["parliament"])
filter_words.update(["part"])
filter_words.update(["part assembler"])
filter_words.update(["participant"])
filter_words.update(["participation"])
filter_words.update(["particular concern"])
filter_words.update(["partisan posturing"])
filter_words.update(["partisanship"])
filter_words.update(["partner"])
filter_words.update(["partnership"])
filter_words.update(["partnership"])
filter_words.update(["party"])
filter_words.update(["party official"])
filter_words.update(["party volunteer"])
filter_words.update(["pas welfare reform"])
filter_words.update(["pastlike"])
filter_words.update(["path forward"])
filter_words.update(["pathway"])
filter_words.update(["patience"])
filter_words.update(["patrick stewart"])
filter_words.update(["patriot"])
filter_words.update(["pattern"])
filter_words.update(["paul j manafort"])
filter_words.update(["paul manafort"])
filter_words.update(["payment"])
filter_words.update(["payment wasnt"])
filter_words.update(["payroll"])
filter_words.update(["peak"])
filter_words.update(["pen"])
filter_words.update(["peninsula"])
filter_words.update(["pennsylvania"])
filter_words.update(["pennsylvania state"])
filter_words.update(["penny"])
filter_words.update(["pentagon boost"])
filter_words.update(["people life"])
filter_words.update(["people premium"])
filter_words.update(["perception"])
filter_words.update(["performance"])
filter_words.update(["peril"])
filter_words.update(["period"])
filter_words.update(["permission"])
filter_words.update(["permit"])
filter_words.update(["permit issue"])
filter_words.update(["persecutionibm"])
filter_words.update(["person"])
filter_words.update(["person"])
filter_words.update(["personathat"])
filter_words.update(["personnel"])
filter_words.update(["perspective"])
filter_words.update(["peter carr"])
filter_words.update(["peterson institute"])
filter_words.update(["pew"])
filter_words.update(["pew research center global attitude"])
filter_words.update(["phase"])
filter_words.update(["phil levy"])
filter_words.update(["philadelphia"])
filter_words.update(["philanthropic effort"])
filter_words.update(["philanthropy"])
filter_words.update(["philippine"])
filter_words.update(["philosophizing"])
filter_words.update(["philosophy"])
filter_words.update(["phoenix mayor greg stanton"])
filter_words.update(["phone"])
filter_words.update(["phone call"])
filter_words.update(["phone call reoffering"])
filter_words.update(["phone conversation"])
filter_words.update(["photo"])
filter_words.update(["phrase"])
filter_words.update(["physician"])
filter_words.update(["picture"])
filter_words.update(["piece"])
filter_words.update(["pig invasion"])
filter_words.update(["pile"])
filter_words.update(["pitfall"])
filter_words.update(["pittsburgh"])
filter_words.update(["place"])
filter_words.update(["plain"])
filter_words.update(["plan"])
filter_words.update(["planning"])
filter_words.update(["plant"])
filter_words.update(["plant"])
filter_words.update(["plant closing plan"])
filter_words.update(["platform"])
filter_words.update(["player"])
filter_words.update(["playground"])
filter_words.update(["playing field"])
filter_words.update(["plea"])
filter_words.update(["pleasantness"])
filter_words.update(["pledge"])
filter_words.update(["pledge"])
filter_words.update(["plenty"])
filter_words.update(["plenty"])
filter_words.update(["plurality"])
filter_words.update(["pm"])
filter_words.update(["pocketbook"])
filter_words.update(["point"])
filter_words.update(["pointshe"])
filter_words.update(["pole"])
filter_words.update(["police helicopter"])
filter_words.update(["policy agenda"])
filter_words.update(["policy area"])
filter_words.update(["policy change"])
filter_words.update(["policy doctrine"])
filter_words.update(["policy expert"])
filter_words.update(["policy goal"])
filter_words.update(["policy maker"])
filter_words.update(["policy option"])
filter_words.update(["policy position"])
filter_words.update(["policy problem"])
filter_words.update(["policy staffer"])
filter_words.update(["policy study"])
filter_words.update(["policy team"])
filter_words.update(["policy time"])
filter_words.update(["policy victory"])
filter_words.update(["policy wonk"])
filter_words.update(["politeness"])
filter_words.update(["politician action"])
filter_words.update(["politics"])
filter_words.update(["poll"])
filter_words.update(["poll"])
filter_words.update(["pollster"])
filter_words.update(["pomerleau note"])
filter_words.update(["pool"])
filter_words.update(["population"])
filter_words.update(["populist movement"])
filter_words.update(["portfolio"])
filter_words.update(["portion"])
filter_words.update(["position"])
filter_words.update(["position bare"])
filter_words.update(["position tomorrow"])
filter_words.update(["posting"])
filter_words.update(["posture"])
filter_words.update(["potential"])
filter_words.update(["pound"])
filter_words.update(["poverty"])
filter_words.update(["power"])
filter_words.update(["power belongs"])
filter_words.update(["power budget"])
filter_words.update(["power job"])
filter_words.update(["power plan"])
filter_words.update(["power plant"])
filter_words.update(["power plant owner"])
filter_words.update(["practice"])
filter_words.update(["praise"])
filter_words.update(["prayer"])
filter_words.update(["precondition"])
filter_words.update(["precursor"])
filter_words.update(["predecessor"])
filter_words.update(["prediction"])
filter_words.update(["preference"])
filter_words.update(["premise"])
filter_words.update(["premium"])
filter_words.update(["premium"])
filter_words.update(["preparation"])
filter_words.update(["prerogative"])
filter_words.update(["presidency"])
filter_words.update(["president chuck jones"])
filter_words.update(["president isnt"])
filter_words.update(["president meant"])
filter_words.update(["president meet"])
filter_words.update(["president proposal"])
filter_words.update(["president push"])
filter_words.update(["president submit"])
filter_words.update(["presidentelects indebtedness"])
filter_words.update(["presidentelects job plan"])
filter_words.update(["presidential personnel johnny destefano"])
filter_words.update(["pressure"])
filter_words.update(["price"])
filter_words.update(["price increase"])
filter_words.update(["price tag"])
filter_words.update(["pricetag"])
filter_words.update(["pricey plan"])
filter_words.update(["prime"])
filter_words.update(["prime minister erna solberg"])
filter_words.update(["principle"])
filter_words.update(["principle"])
filter_words.update(["priority"])
filter_words.update(["priority"])
filter_words.update(["prison sentence"])
filter_words.update(["pristine view"])
filter_words.update(["privacy"])
filter_words.update(["privilege"])
filter_words.update(["probability"])
filter_words.update(["problem"])
filter_words.update(["process"])
filter_words.update(["proclaim"])
filter_words.update(["proclamation"])
filter_words.update(["procurement"])
filter_words.update(["producer"])
filter_words.update(["product"])
filter_words.update(["productbyproduct"])
filter_words.update(["production"])
filter_words.update(["productivity"])
filter_words.update(["profile lawmaker"])
filter_words.update(["profit"])
filter_words.update(["profit"])
filter_words.update(["program"])
filter_words.update(["program point"])
filter_words.update(["progress"])
filter_words.update(["progress"])
filter_words.update(["progressive"])
filter_words.update(["progressiveness"])
filter_words.update(["prohibition"])
filter_words.update(["project"])
filter_words.update(["project promoter"])
filter_words.update(["proliferation"])
filter_words.update(["proliferation fraught"])
filter_words.update(["promise"])
filter_words.update(["promote"])
filter_words.update(["promoter"])
filter_words.update(["property"])
filter_words.update(["property likewise state"])
filter_words.update(["property right"])
filter_words.update(["proponent"])
filter_words.update(["proposal"])
filter_words.update(["proposal million"])
filter_words.update(["proposition"])
filter_words.update(["proprietorship"])
filter_words.update(["prosecutor"])
filter_words.update(["prospect"])
filter_words.update(["prosperity"])
filter_words.update(["protection"])
filter_words.update(["protection"])
filter_words.update(["protection fund"])
filter_words.update(["protectionism"])
filter_words.update(["protest"])
filter_words.update(["protester"])
filter_words.update(["provider"])
filter_words.update(["proving"])
filter_words.update(["provision"])
filter_words.update(["proworker"])
filter_words.update(["public"])
filter_words.update(["publication"])
filter_words.update(["publisher"])
filter_words.update(["publisher simon"])
filter_words.update(["pulpit"])
filter_words.update(["purist"])
filter_words.update(["pursuant"])
filter_words.update(["push"])
filter_words.update(["put"])
filter_words.update(["qualitative"])
filter_words.update(["qualm"])
filter_words.update(["quarter"])
filter_words.update(["quarter point"])
filter_words.update(["quest"])
filter_words.update(["question"])
filter_words.update(["questionfor"])
filter_words.update(["quinnipiac university"])
filter_words.update(["race"])
filter_words.update(["race"])
filter_words.update(["rachael bade"])
filter_words.update(["rachel stohl"])
filter_words.update(["rail"])
filter_words.update(["rally"])
filter_words.update(["rand corporation"])
filter_words.update(["rand paul"])
filter_words.update(["range"])
filter_words.update(["range"])
filter_words.update(["rank"])
filter_words.update(["rariz"])
filter_words.update(["rate"])
filter_words.update(["rate today"])
filter_words.update(["rating"])
filter_words.update(["rationale"])
filter_words.update(["reaction"])
filter_words.update(["read"])
filter_words.update(["reader"])
filter_words.update(["realignment"])
filter_words.update(["realism"])
filter_words.update(["reality"])
filter_words.update(["reason"])
filter_words.update(["reboot"])
filter_words.update(["rebound"])
filter_words.update(["rebuilding project"])
filter_words.update(["rebuilds"])
filter_words.update(["rebuke"])
filter_words.update(["reception"])
filter_words.update(["recipient"])
filter_words.update(["reckless"])
filter_words.update(["record"])
filter_words.update(["record"])
filter_words.update(["record high"])
filter_words.update(["record speed"])
filter_words.update(["record straight"])
filter_words.update(["recovery"])
filter_words.update(["redesignation"])
filter_words.update(["reduction"])
filter_words.update(["reelection"])
filter_words.update(["reevaluation"])
filter_words.update(["reference"])
filter_words.update(["reflection"])
filter_words.update(["reform"])
filter_words.update(["regard"])
filter_words.update(["region"])
filter_words.update(["register notice"])
filter_words.update(["registry"])
filter_words.update(["regulator"])
filter_words.update(["reich"])
filter_words.update(["reimbursement program"])
filter_words.update(["reiteration"])
filter_words.update(["rejection"])
filter_words.update(["relation"])
filter_words.update(["relation"])
filter_words.update(["relationship"])
filter_words.update(["release"])
filter_words.update(["relegation"])
filter_words.update(["reliability"])
filter_words.update(["reliant"])
filter_words.update(["relief"])
filter_words.update(["remark"])
filter_words.update(["remedy"])
filter_words.update(["renee ellmers"])
filter_words.update(["renmin university"])
filter_words.update(["rep ileana roslehtinen"])
filter_words.update(["rep jim jordan"])
filter_words.update(["rep mark meadow"])
filter_words.update(["rep steve king"])
filter_words.update(["rep tom cole"])
filter_words.update(["rep tom davis"])
filter_words.update(["rep zoe lofgren"])
filter_words.update(["repair"])
filter_words.update(["repercussion"])
filter_words.update(["replacement"])
filter_words.update(["replacement cut"])
filter_words.update(["report"])
filter_words.update(["reporter saturday"])
filter_words.update(["represent"])
filter_words.update(["representative"])
filter_words.update(["representative mario diazbalart"])
filter_words.update(["republican operative doug heye"])
filter_words.update(["republican rep mia love"])
filter_words.update(["republican strategist alex conant"])
filter_words.update(["reputation"])
filter_words.update(["request"])
filter_words.update(["requirement"])
filter_words.update(["rescission"])
filter_words.update(["rescuing american"])
filter_words.update(["research"])
filter_words.update(["research"])
filter_words.update(["research associate"])
filter_words.update(["reserve"])
filter_words.update(["resettlement agency"])
filter_words.update(["resident"])
filter_words.update(["resilience"])
filter_words.update(["resiliency"])
filter_words.update(["resolute desk"])
filter_words.update(["resolution"])
filter_words.update(["resolve"])
filter_words.update(["resonance"])
filter_words.update(["resource"])
filter_words.update(["resource"])
filter_words.update(["respect"])
filter_words.update(["respond"])
filter_words.update(["respondent"])
filter_words.update(["respondent view"])
filter_words.update(["responsibility"])
filter_words.update(["responsibility"])
filter_words.update(["rest"])
filter_words.update(["restraint"])
filter_words.update(["restriction"])
filter_words.update(["result"])
filter_words.update(["resume"])
filter_words.update(["resurgence"])
filter_words.update(["retaliation"])
filter_words.update(["retirement"])
filter_words.update(["retribution"])
filter_words.update(["return"])
filter_words.update(["reutersmike blake a white house spokeswoman"])
filter_words.update(["revelation"])
filter_words.update(["reverberate"])
filter_words.update(["reversal"])
filter_words.update(["review"])
filter_words.update(["review period"])
filter_words.update(["revocation"])
filter_words.update(["rexnord"])
filter_words.update(["rexnord corp"])
filter_words.update(["rich"])
filter_words.update(["right"])
filter_words.update(["right consideration"])
filter_words.update(["right group"])
filter_words.update(["right record"])
filter_words.update(["rise"])
filter_words.update(["risk"])
filter_words.update(["ritual"])
filter_words.update(["rival"])
filter_words.update(["rnev"])
filter_words.update(["road"])
filter_words.update(["roadblock"])
filter_words.update(["roadmap"])
filter_words.update(["robert james"])
filter_words.update(["rock"])
filter_words.update(["rocket man"])
filter_words.update(["rockier relationship"])
filter_words.update(["rodriguez"])
filter_words.update(["roger stone"])
filter_words.update(["role"])
filter_words.update(["ron johnson"])
filter_words.update(["room"])
filter_words.update(["roosevelt room"])
filter_words.update(["root"])
filter_words.update(["rote phrase"])
filter_words.update(["round"])
filter_words.update(["roundup"])
filter_words.update(["route"])
filter_words.update(["row"])
filter_words.update(["rtenn"])
filter_words.update(["rtex"])
filter_words.update(["rule"])
filter_words.update(["rule change"])
filter_words.update(["rule making"])
filter_words.update(["rulebook"])
filter_words.update(["rumbling"])
filter_words.update(["rus feingold"])
filter_words.update(["rust"])
filter_words.update(["saber"])
filter_words.update(["sacrifice"])
filter_words.update(["safety"])
filter_words.update(["safety regulation"])
filter_words.update(["sajwani"])
filter_words.update(["sajwanis family"])
filter_words.update(["sake"])
filter_words.update(["sale"])
filter_words.update(["sale force"])
filter_words.update(["sale friday"])
filter_words.update(["sale record"])
filter_words.update(["salesman"])
filter_words.update(["salt"])
filter_words.update(["sandalow"])
filter_words.update(["saturday morning"])
filter_words.update(["saving"])
filter_words.update(["say"])
filter_words.update(["scandal"])
filter_words.update(["scenario"])
filter_words.update(["scene"])
filter_words.update(["schedule"])
filter_words.update(["schedule president trump"])
filter_words.update(["school choice argue"])
filter_words.update(["school choice policy"])
filter_words.update(["schooling"])
filter_words.update(["schumer"])
filter_words.update(["schuster"])
filter_words.update(["science"])
filter_words.update(["science professor"])
filter_words.update(["science study"])
filter_words.update(["scientist"])
filter_words.update(["scoop"])
filter_words.update(["scope"])
filter_words.update(["score"])
filter_words.update(["screening"])
filter_words.update(["scrutiny"])
filter_words.update(["sea level rise continue"])
filter_words.update(["seaport"])
filter_words.update(["search"])
filter_words.update(["search history"])
filter_words.update(["seat"])
filter_words.update(["sec"])
filter_words.update(["secretary"])
filter_words.update(["section"])
filter_words.update(["sector"])
filter_words.update(["security adviser"])
filter_words.update(["security analyst"])
filter_words.update(["security barricade"])
filter_words.update(["security issue"])
filter_words.update(["security measure"])
filter_words.update(["security number"])
filter_words.update(["security official"])
filter_words.update(["security purpose"])
filter_words.update(["seeking other partnership"])
filter_words.update(["seen"])
filter_words.update(["self"])
filter_words.update(["self interest"])
filter_words.update(["selfdefense"])
filter_words.update(["selfinterest"])
filter_words.update(["selfregulate"])
filter_words.update(["sen"])
filter_words.update(["senate"])
filter_words.update(["senate majority leader"])
filter_words.update(["senate majority leader howard baker"])
filter_words.update(["senate minority leader charles e schumer"])
filter_words.update(["senate rule"])
filter_words.update(["senate seat"])
filter_words.update(["sense"])
filter_words.update(["sensor"])
filter_words.update(["sentence"])
filter_words.update(["sentiment"])
filter_words.update(["series"])
filter_words.update(["service"])
filter_words.update(["service equivalent"])
filter_words.update(["service program"])
filter_words.update(["service provider"])
filter_words.update(["session"])
filter_words.update(["sessionsand"])
filter_words.update(["set"])
filter_words.update(["set"])
filter_words.update(["setback"])
filter_words.update(["setting"])
filter_words.update(["settlement"])
filter_words.update(["shale"])
filter_words.update(["shape"])
filter_words.update(["share"])
filter_words.update(["share"])
filter_words.update(["shareholder"])
filter_words.update(["shift"])
filter_words.update(["shine"])
filter_words.update(["ship"])
filter_words.update(["shipping firm"])
filter_words.update(["shirt"])
filter_words.update(["shock"])
filter_words.update(["shock wave"])
filter_words.update(["shopkeeper"])
filter_words.update(["shore"])
filter_words.update(["short"])
filter_words.update(["shortage"])
filter_words.update(["shortsightedness"])
filter_words.update(["shot"])
filter_words.update(["shovel"])
filter_words.update(["show"])
filter_words.update(["sick"])
filter_words.update(["side effect"])
filter_words.update(["sight"])
filter_words.update(["sign"])
filter_words.update(["signal"])
filter_words.update(["signature moment"])
filter_words.update(["signing ceremony"])
filter_words.update(["similarity"])
filter_words.update(["simplest term"])
filter_words.update(["simplification act"])
filter_words.update(["sin"])
filter_words.update(["single"])
filter_words.update(["sit"])
filter_words.update(["sitdown"])
filter_words.update(["site"])
filter_words.update(["situation"])
filter_words.update(["skeptic"])
filter_words.update(["skin"])
filter_words.update(["sky"])
filter_words.update(["slam"])
filter_words.update(["slap"])
filter_words.update(["slew"])
filter_words.update(["slice"])
filter_words.update(["slick"])
filter_words.update(["slight"])
filter_words.update(["smoking gun"])
filter_words.update(["social science"])
filter_words.update(["social sciences"])
filter_words.update(["social security"])
filter_words.update(["socialism"])
filter_words.update(["society"])
filter_words.update(["soil"])
filter_words.update(["solution"])
filter_words.update(["somebody"])
filter_words.update(["someone"])
filter_words.update(["someone"])
filter_words.update(["something happens"])
filter_words.update(["son"])
filter_words.update(["soninlaw"])
filter_words.update(["soontobepresident"])
filter_words.update(["sort"])
filter_words.update(["soul"])
filter_words.update(["source"])
filter_words.update(["souring"])
filter_words.update(["south"])
filter_words.update(["south carolina"])
filter_words.update(["south carolina republican"])
filter_words.update(["south dakota"])
filter_words.update(["southeast"])
filter_words.update(["sovereignty"])
filter_words.update(["speak"])
filter_words.update(["speaker"])
filter_words.update(["speaker newt gingrich"])
filter_words.update(["spear"])
filter_words.update(["specie"])
filter_words.update(["specific"])
filter_words.update(["spectacle"])
filter_words.update(["spectrum"])
filter_words.update(["speculation"])
filter_words.update(["speech monday"])
filter_words.update(["speed"])
filter_words.update(["spend"])
filter_words.update(["spending"])
filter_words.update(["spending level"])
filter_words.update(["spent"])
filter_words.update(["spike"])
filter_words.update(["spirit"])
filter_words.update(["spite"])
filter_words.update(["spoke"])
filter_words.update(["spokesman"])
filter_words.update(["spokesperson"])
filter_words.update(["spokeswoman"])
filter_words.update(["sport"])
filter_words.update(["sportsman"])
filter_words.update(["spot"])
filter_words.update(["spouse"])
filter_words.update(["spread"])
filter_words.update(["spring"])
filter_words.update(["spring session"])
filter_words.update(["spy"])
filter_words.update(["square"])
filter_words.update(["staff"])
filter_words.update(["staff he"])
filter_words.update(["staffed"])
filter_words.update(["staffer"])
filter_words.update(["stage"])
filter_words.update(["stage name"])
filter_words.update(["stake"])
filter_words.update(["stake"])
filter_words.update(["stance"])
filter_words.update(["stand"])
filter_words.update(["standard"])
filter_words.update(["stanford university"])
filter_words.update(["stanton"])
filter_words.update(["star"])
filter_words.update(["stark"])
filter_words.update(["start"])
filter_words.update(["start"])
filter_words.update(["start date"])
filter_words.update(["starving"])
filter_words.update(["state business"])
filter_words.update(["state councilor yang jiechi"])
filter_words.update(["state department"])
filter_words.update(["state department official"])
filter_words.update(["state department staff"])
filter_words.update(["state duma"])
filter_words.update(["state employee"])
filter_words.update(["state senate president"])
filter_words.update(["state win"])
filter_words.update(["statement"])
filter_words.update(["statement read"])
filter_words.update(["statement saturday afternoon"])
filter_words.update(["status"])
filter_words.update(["status quo"])
filter_words.update(["stay"])
filter_words.update(["steel case"])
filter_words.update(["stem"])
filter_words.update(["step"])
filter_words.update(["steroid"])
filter_words.update(["stick"])
filter_words.update(["stiletto heel"])
filter_words.update(["stimulation"])
filter_words.update(["stint"])
filter_words.update(["stop"])
filter_words.update(["stopgap"])
filter_words.update(["story"])
filter_words.update(["storyline"])
filter_words.update(["stranger"])
filter_words.update(["strategic"])
filter_words.update(["strategist"])
filter_words.update(["strategy"])
filter_words.update(["strategy"])
filter_words.update(["stream"])
filter_words.update(["street"])
filter_words.update(["strength"])
filter_words.update(["stress"])
filter_words.update(["stretch"])
filter_words.update(["stricter regulation"])
filter_words.update(["stride"])
filter_words.update(["string"])
filter_words.update(["stroke"])
filter_words.update(["structure"])
filter_words.update(["struggle"])
filter_words.update(["student"])
filter_words.update(["study"])
filter_words.update(["study"])
filter_words.update(["stuff"])
filter_words.update(["subject"])
filter_words.update(["submission"])
filter_words.update(["subsection"])
filter_words.update(["subsection b"])
filter_words.update(["subsection e"])
filter_words.update(["substance"])
filter_words.update(["success"])
filter_words.update(["success breed success"])
filter_words.update(["suggestion"])
filter_words.update(["suggests"])
filter_words.update(["suit"])
filter_words.update(["summation"])
filter_words.update(["summer"])
filter_words.update(["summer recess"])
filter_words.update(["summit"])
filter_words.update(["sunday afternoon"])
filter_words.update(["superpower"])
filter_words.update(["superpower chooses"])
filter_words.update(["supplier"])
filter_words.update(["support"])
filter_words.update(["support trump"])
filter_words.update(["supporter"])
filter_words.update(["supreme court today"])
filter_words.update(["surge"])
filter_words.update(["surprise"])
filter_words.update(["survey"])
filter_words.update(["survey"])
filter_words.update(["suspend"])
filter_words.update(["svr"])
filter_words.update(["swamp"])
filter_words.update(["swath"])
filter_words.update(["swing vote"])
filter_words.update(["sympathizer"])
filter_words.update(["symptom"])
filter_words.update(["system"])
filter_words.update(["system operator"])
filter_words.update(["tab"])
filter_words.update(["table"])
filter_words.update(["table range"])
filter_words.update(["tactic"])
filter_words.update(["talk"])
filter_words.update(["tandem"])
filter_words.update(["tantamount"])
filter_words.update(["taoyuan"])
filter_words.update(["tape"])
filter_words.update(["target"])
filter_words.update(["target"])
filter_words.update(["target date"])
filter_words.update(["tarmac"])
filter_words.update(["task"])
filter_words.update(["teacher"])
filter_words.update(["teaching"])
filter_words.update(["team"])
filter_words.update(["tear"])
filter_words.update(["technology platform"])
filter_words.update(["television"])
filter_words.update(["television interview"])
filter_words.update(["tem"])
filter_words.update(["temperature"])
filter_words.update(["template"])
filter_words.update(["ten"])
filter_words.update(["tendency"])
filter_words.update(["tenet"])
filter_words.update(["tenor"])
filter_words.update(["tension"])
filter_words.update(["tenure"])
filter_words.update(["term"])
filter_words.update(["terminal high altitude area defense"])
filter_words.update(["termination"])
filter_words.update(["terror problem region"])
filter_words.update(["terry fleming"])
filter_words.update(["test"])
filter_words.update(["test case"])
filter_words.update(["texan"])
filter_words.update(["texas civil right project"])
filter_words.update(["texas landowner"])
filter_words.update(["thank"])
filter_words.update(["thanks"])
filter_words.update(["thats"])
filter_words.update(["thaw"])
filter_words.update(["theatrics"])
filter_words.update(["theme park"])
filter_words.update(["theory"])
filter_words.update(["theory everybody"])
filter_words.update(["therefrom"])
filter_words.update(["theyre"])
filter_words.update(["thing"])
filter_words.update(["thing happen"])
filter_words.update(["think"])
filter_words.update(["think tank"])
filter_words.update(["thinking"])
filter_words.update(["thinkprogress"])
filter_words.update(["thinkprogresss source"])
filter_words.update(["third"])
filter_words.update(["thirdparties"])
filter_words.update(["thomas kinnaman"])
filter_words.update(["thomas watson"])
filter_words.update(["thorn"])
filter_words.update(["thought"])
filter_words.update(["thousand"])
filter_words.update(["threat"])
filter_words.update(["thrust"])
filter_words.update(["thug"])
filter_words.update(["thumb"])
filter_words.update(["thursday meeting"])
filter_words.update(["thursday morning"])
filter_words.update(["thursday night"])
filter_words.update(["ticket"])
filter_words.update(["tie"])
filter_words.update(["time report"])
filter_words.update(["time trump"])
filter_words.update(["timeline"])
filter_words.update(["timing"])
filter_words.update(["tip"])
filter_words.update(["title"])
filter_words.update(["to whom it may concern"])
filter_words.update(["today im"])
filter_words.update(["tokyo thursday"])
filter_words.update(["toledo"])
filter_words.update(["toledo lunch"])
filter_words.update(["toll"])
filter_words.update(["tone"])
filter_words.update(["tone"])
filter_words.update(["tool"])
filter_words.update(["topic"])
filter_words.update(["touchdown"])
filter_words.update(["tour"])
filter_words.update(["towards"])
filter_words.update(["track"])
filter_words.update(["tractor"])
filter_words.update(["tradeoff"])
filter_words.update(["trading"])
filter_words.update(["traffic"])
filter_words.update(["traffic congestion"])
filter_words.update(["training certification"])
filter_words.update(["trans canada"])
filter_words.update(["transaction"])
filter_words.update(["transcriptionist"])
filter_words.update(["transformation"])
filter_words.update(["transgender right"])
filter_words.update(["transit"])
filter_words.update(["transition"])
filter_words.update(["transition people"])
filter_words.update(["transition phase"])
filter_words.update(["transition team"])
filter_words.update(["transparency"])
filter_words.update(["transportation"])
filter_words.update(["travel plan"])
filter_words.update(["treasury"])
filter_words.update(["treat"])
filter_words.update(["treatment"])
filter_words.update(["tree"])
filter_words.update(["trend"])
filter_words.update(["trend line"])
filter_words.update(["trepidation"])
filter_words.update(["trigger"])
filter_words.update(["trio"])
filter_words.update(["trip"])
filter_words.update(["trip"])
filter_words.update(["trip van noppen"])
filter_words.update(["troop"])
filter_words.update(["trouble"])
filter_words.update(["truck"])
filter_words.update(["truck manufacturing"])
filter_words.update(["trucking company"])
filter_words.update(["trump administration plan"])
filter_words.update(["trump adviser leonard leo"])
filter_words.update(["trump agenda"])
filter_words.update(["trump cabinet member"])
filter_words.update(["trump child"])
filter_words.update(["trump lawyer john dowd"])
filter_words.update(["trump name"])
filter_words.update(["trump proposal"])
filter_words.update(["trump spokesman sean spicer"])
filter_words.update(["trump team"])
filter_words.update(["trump voter"])
filter_words.update(["trumps desk"])
filter_words.update(["trust"])
filter_words.update(["tucson"])
filter_words.update(["Tuesday"])
filter_words.update(["tuesday meeting"])
filter_words.update(["tuesday night"])
filter_words.update(["tune"])
filter_words.update(["turmoil"])
filter_words.update(["turn"])
filter_words.update(["turn"])
filter_words.update(["turnout"])
filter_words.update(["turnover cost"])
filter_words.update(["tv"])
filter_words.update(["twelve"])
filter_words.update(["twist"])
filter_words.update(["ty cobb"])
filter_words.update(["type"])
filter_words.update(["u history"])
filter_words.update(["u outer continental shelf"])
filter_words.update(["u pacific"])
filter_words.update(["u resident"])
filter_words.update(["u territory"])
filter_words.update(["u value"])
filter_words.update(["u weaker"])
filter_words.update(["uber"])
filter_words.update(["ucirvine"])
filter_words.update(["ukraine"])
filter_words.update(["un chamber"])
filter_words.update(["unbeknownst"])
filter_words.update(["unblocking"])
filter_words.update(["uncertainty"])
filter_words.update(["uncle"])
filter_words.update(["understanding"])
filter_words.update(["undoes rule"])
filter_words.update(["union address"])
filter_words.update(["unit"])
filter_words.update(["united nation"])
filter_words.update(["united state ability"])
filter_words.update(["united state feel"])
filter_words.update(["united statesled bay"])
filter_words.update(["unity"])
filter_words.update(["universal"])
filter_words.update(["unpredictability"])
filter_words.update(["unravelling"])
filter_words.update(["update"])
filter_words.update(["upon"])
filter_words.update(["upsetting"])
filter_words.update(["us chamber"])
filter_words.update(["us commitment"])
filter_words.update(["us court"])
filter_words.update(["us custom"])
filter_words.update(["us custom sign"])
filter_words.update(["us department"])
filter_words.update(["us departure"])
filter_words.update(["us direction"])
filter_words.update(["us exodus"])
filter_words.update(["us favorability"])
filter_words.update(["us february"])
filter_words.update(["us good"])
filter_words.update(["us government"])
filter_words.update(["us loss"])
filter_words.update(["us representative devin nunes"])
filter_words.update(["use"])
filter_words.update(["user"])
filter_words.update(["user data"])
filter_words.update(["usimage copyrightgetty image image caption"])
filter_words.update(["uss misunderstanding"])
filter_words.update(["utilization"])
filter_words.update(["vacancy"])
filter_words.update(["valliere"])
filter_words.update(["value"])
filter_words.update(["van jackson"])
filter_words.update(["vanquished democratic"])
filter_words.update(["variation"])
filter_words.update(["variety"])
filter_words.update(["vehicle"])
filter_words.update(["verge"])
filter_words.update(["verification processesmay"])
filter_words.update(["vermont"])
filter_words.update(["version"])
filter_words.update(["very fundamental"])
filter_words.update(["veto"])
filter_words.update(["vetting"])
filter_words.update(["vetting policy"])
filter_words.update(["vetting procedure"])
filter_words.update(["victory"])
filter_words.update(["view"])
filter_words.update(["violent"])
filter_words.update(["virginia canter"])
filter_words.update(["virginia governor"])
filter_words.update(["virginia vineyard"])
filter_words.update(["virtue"])
filter_words.update(["visibility"])
filter_words.update(["visit"])
filter_words.update(["visitor"])
filter_words.update(["voice"])
filter_words.update(["volume"])
filter_words.update(["volunteer"])
filter_words.update(["voting"])
filter_words.update(["vow"])
filter_words.update(["vpn"])
filter_words.update(["wa"])
filter_words.update(["wage growth"])
filter_words.update(["wait"])
filter_words.update(["waiver"])
filter_words.update(["wake"])
filter_words.update(["walid phares"])
filter_words.update(["walk"])
filter_words.update(["war"])
filter_words.update(["warning"])
filter_words.update(["warrior"])
filter_words.update(["warsaw"])
filter_words.update(["was trump"])
filter_words.update(["washing machine case"])
filter_words.update(["washington state lawsuit"])
filter_words.update(["waste"])
filter_words.update(["water"])
filter_words.update(["waterway"])
filter_words.update(["wave"])
filter_words.update(["way"])
filter_words.update(["way conservative"])
filter_words.update(["weather"])
filter_words.update(["wedge"])
filter_words.update(["wednesday morning"])
filter_words.update(["wednesday night"])
filter_words.update(["weekend"])
filter_words.update(["weight"])
filter_words.update(["welcome"])
filter_words.update(["well"])
filter_words.update(["wellbeing"])
filter_words.update(["west"])
filter_words.update(["west coast headquarters"])
filter_words.update(["west java"])
filter_words.update(["west virginia"])
filter_words.update(["western building"])
filter_words.update(["western world"])
filter_words.update(["westernled"])
filter_words.update(["whats"])
filter_words.update(["whiff"])
filter_words.update(["whirl"])
filter_words.update(["white house connection"])
filter_words.update(["white house document"])
filter_words.update(["white house meeting"])
filter_words.update(["white house move"])
filter_words.update(["white house press secretary sean spicer"])
filter_words.update(["white houses official announcement"])
filter_words.update(["whole"])
filter_words.update(["wife"])
filter_words.update(["wiggle room"])
filter_words.update(["wilbur l ross jr"])
filter_words.update(["wildlife"])
filter_words.update(["william pryor"])
filter_words.update(["willingness"])
filter_words.update(["window"])
filter_words.update(["winery"])
filter_words.update(["winner"])
filter_words.update(["winter"])
filter_words.update(["wisconsin"])
filter_words.update(["wisconsin institution"])
filter_words.update(["wisconsinite"])
filter_words.update(["wisdom"])
filter_words.update(["wish"])
filter_words.update(["witness"])
filter_words.update(["woman"])
filter_words.update(["word"])
filter_words.update(["work"])
filter_words.update(["worked"])
filter_words.update(["workforce"])
filter_words.update(["working relationship"])
filter_words.update(["working till"])
filter_words.update(["workplace perspective"])
filter_words.update(["world firm"])
filter_words.update(["world isnt"])
filter_words.update(["world leader"])
filter_words.update(["world order"])
filter_words.update(["world power"])
filter_words.update(["world think"])
filter_words.update(["world war ii"])
filter_words.update(["worry"])
filter_words.update(["worrying"])
filter_words.update(["worse"])
filter_words.update(["worth"])
filter_words.update(["wrestler"])
filter_words.update(["wrinkle"])
filter_words.update(["wrong"])
filter_words.update(["wrongdoing"])
filter_words.update(["wyoming"])
filter_words.update(["xavier becerra"])
filter_words.update(["xie zhenhua"])
filter_words.update(["yacht"])
filter_words.update(["yale program"])
filter_words.update(["yeah"])
filter_words.update(["year appropriation work"])
filter_words.update(["year debut"])
filter_words.update(["year election"])
filter_words.update(["yearban"])
filter_words.update(["yesterday american"])
filter_words.update(["youre"])
filter_words.update(["youve"])
filter_words.update(["ziglar"])
filter_words.update(["zone"])
filter_words.update(["aid"])
filter_words.update(["benefit"])
filter_words.update(["choice"])
filter_words.update(["1990s"])
filter_words.update(["ability"])
filter_words.update(["bluffing"])
filter_words.update(["certificate"])
filter_words.update(["defender"])
filter_words.update(["four season hotel"])
filter_words.update(["four seasons hotel"])
filter_words.update(["institution stock"])
filter_words.update(["peace"])
filter_words.update(["stephen curry"])
filter_words.update(["trustee"])
filter_words.update(["truth"])
filter_words.update(["accident"])
filter_words.update(["announce"])
filter_words.update(["applause"])
filter_words.update(["celebrity golf tournament"])
filter_words.update(["certification"])
filter_words.update(["central park"])
filter_words.update(["coastline"])
filter_words.update(["desert town"])
filter_words.update(["eastern district"])
filter_words.update(["bush administration official"])
filter_words.update(["bush appointee"])
filter_words.update(["george w bush presidency"])
filter_words.update(["george w bushera level"])
filter_words.update(["george w bushera rhetoric"])
filter_words.update(["georgeBush"])
filter_words.update(["alamo"])
filter_words.update(["committee room"])
filter_words.update(["alberta"])
filter_words.update(["chris warren"])
filter_words.update(["nfl"])
filter_words.update(["bill clinton"])
filter_words.update(["billClinton"])
filter_words.update(["air force one"])
filter_words.update(["charter flight"])
filter_words.update(["marine one"])
filter_words.update(["donald trump jr"])
filter_words.update(["eric trump foundation"])
filter_words.update(["family"])
filter_words.update(["lady melania trump"])




#======================End pasted section==============================

pickle.dump(filter_words, open(pickle_path + 'filter_words.p', 'wb'))
